// 新建工作流 Dialog：填名称/描述 → 跳转编辑器
// New workflow dialog: fill name/description → navigate to editor
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { v4 as uuidv4 } from "uuid";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function NewWorkflowDialog({ open, onOpenChange }: Props) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [saving, setSaving] = useState(false);

  const handleCreate = () => {
    if (!name.trim()) return;
    setSaving(true);
    // id 由编辑器在新建时生成；这里只携带 name/description 供预填
    // Id is generated by the editor on create; we pass name/description for pre-fill
    const id = `wf-${uuidv4().replace(/-/g, "")}`;
    // 将 name/description 编码进 URL search params（轻量，无需 store）
    // Encode name/description into URL search params (lightweight, no store needed)
    const params = new URLSearchParams({
      name: name.trim(),
      description: description.trim(),
    });
    navigate(`/workflow/${id}/edit?${params.toString()}`);
    // 重置并关闭 Dialog
    // Reset and close
    setName("");
    setDescription("");
    setSaving(false);
    onOpenChange(false);
  };

  const handleOpenChange = (next: boolean) => {
    if (!next) {
      setName("");
      setDescription("");
    }
    onOpenChange(next);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("workflow.new")}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-2">
            <Label htmlFor="wf-name">
              {t("workflowEditor.name")} <span className="text-destructive">*</span>
            </Label>
            <Input
              id="wf-name"
              placeholder={t("workflowEditor.namePlaceholder")}
              value={name}
              onChange={(e) => setName(e.target.value)}
              maxLength={20}
              autoFocus
              onKeyDown={(e) => {
                if (e.key === "Enter" && name.trim()) handleCreate();
              }}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="wf-desc">
              {t("workflowEditor.description")}
            </Label>
            <Input
              id="wf-desc"
              placeholder={t("workflowEditor.descriptionPlaceholder")}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => handleOpenChange(false)}>
            {t("common.cancel")}
          </Button>
          <Button onClick={handleCreate} disabled={!name.trim() || saving}>
            {saving ? t("workflow.saving") : t("workflow.new")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}